### ISSUE TITLE
Game crashed after trying to load single player world after playing on the official server

### ISSUE THREAD

**Issue by Dr-Game** [SmashingMods/antimatter-chemistry#167]
Crash report
[crash-2019-08-04_10.30.31-server.txt](https://github.com/al132mc/antimatter-chemistry/files/3465033/crash-2019-08-04_10.30.31-server.txt)

**Comment by al132mc** [comment]
I do see this crash from time to time, but usually starting up the game and trying to open the world will resolve it...

**Comment by Dr-Game** [comment]
Yeah, it's just a minor annoyance. It doesn't take but a few minutes to relaunch the game for me, but a crash is still a crash, and I thought reporting it would help.

**Comment by MasterEnderman** [comment]
Duplicate of #44
