### ISSUE TITLE
Game crashed while in Crafting station

### ISSUE THREAD

**Issue by DragonFyreStorm** [SmashingMods/antimatter-chemistry#177]
[crash-2019-08-10_18.02.52-client.txt](https://github.com/al132mc/antimatter-chemistry/files/3489338/crash-2019-08-10_18.02.52-client.txt)
[crash-2019-08-10_18.12.41-client.txt](https://github.com/al132mc/antimatter-chemistry/files/3489339/crash-2019-08-10_18.12.41-client.txt)

**Comment by al132mc** [comment]
Known bug that has something to do with specifically crafting compressed cobble in the crafting station, for some reason...

**Comment by TheSnowyChickens** [comment]
Also other types of blocks produce the crash. :(

**Comment by MasterEnderman** [comment]
Duplicate of #161
