### ISSUE TITLE
Disable Cheat on template worlds

### ISSUE THREAD

**Issue by nastybytes** [SmashingMods/antimatter-chemistry#323]
Hi.

I have an issue with the template world, whenever I click on a recipe in JEI, it just give me the item instead of show up the crafting recipe.

Hope you guys fixing it soon :).

**Comment by MasterEnderman** [comment]
Greetings! Which template did you use to create your world?
(For now you can deactivate the "cheat" mode by ctrl+L_clicking the red wrench next to the jei search bar)
