### ISSUE TITLE
Crash related to RFTools Dimensions under different circumstances

### ISSUE THREAD

**Issue by DreaminBoi** [SmashingMods/antimatter-chemistry#44]
So,i just recently update the pack from 1.1.2 to 1.2.0 and when i load my old save from 1.1.2 the game instantly crashed.

Here's the crash report : https://pastebin.com/xpymjsQm
I suspect the cause is extra utilities 2 but i dont know what things caused it

**Comment by al132mc** [comment]
https://github.com/McJtyMods/RFToolsDimensions/issues/252

**Comment by al132mc** [comment]
Has anyone had issues with this lately? It might have been an issue with some other mod that has since been updated.

**Comment by findaldudu** [comment]
I had it once with the same crash report. I was updating from 1.2.5 to 1.2.7. But it didn't crash the second time I load the world.

**Comment by MasterEnderman** [comment]
FYI: The crash won't happen every time. Try restarting the pack and chances are pretty high, that it works fine.

Sadly there's nothing I can do to fix this problem. :/
